- name: Deploy
  hosts: all
  become: yes

  tasks:
    - name: Ansible create file with content example
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {"log-driver": "syslog","log-opts": {"syslog-address": "udp://127.0.0.1:514"}}     
